<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Siva-VAIO" name="TestNGDemoPack.TestNGdemo5" tests="3" failures="0" timestamp="30 Mar 2020 22:17:22 GMT" time="0.279" errors="1">
  <testcase name="Weblogin" time="0.275" classname="TestNGDemoPack.TestNGdemo5">
    <error type="org.testng.internal.thread.ThreadTimeoutException" message="Method TestNGDemoPack.TestNGdemo5.Weblogin() didn&#039;t finish within the time-out 200">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method TestNGDemoPack.TestNGdemo5.Weblogin() didn't finish within the time-out 200
at java.util.concurrent.FutureTask.done(Unknown Source)
at java.util.concurrent.FutureTask.finishCompletion(Unknown Source)
at java.util.concurrent.FutureTask.setException(Unknown Source)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- Weblogin -->
  <testcase name="APIlogin" time="0.002" classname="TestNGDemoPack.TestNGdemo5"/>
  <testcase name="Mobilelogin" time="0.002" classname="TestNGDemoPack.TestNGdemo5"/>
</testsuite> <!-- TestNGDemoPack.TestNGdemo5 -->
